server:
  port: 12330

spring:
  datasource:
    url: jdbc:mysql://81.70.210.113:3306/djpf_jzt?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: kDP2248tJpCxHkmp
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    druid:
      max-active: 10 # 最大活跃数量 默认8
      min-idle:  2 # 最小空闲数 默认0
      initial-size: 5 # 初始连接数
      max-wait: 60000 # 获取连接最大等待时间 默认 -1
      validation-query: select 1
      validation-query-timeout: 60000
      time-between-eviction-runs-millis: 2000 # 间隔多久进行检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 600000 # 配置连接在池中最小生存的时间
      max-wait-thread-count: 20 # 最大等待线程数

mybatis:
  typeAliasesPackage: com.djpf.personnel.entity
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.daji.ureport.console: debug
    com.hikvision.artemis.sdk.ArtemisHttpUtil: off